### ISSUE TITLE
Export Bson->Json->Bson converters

### ISSUE THREAD

**Issue by alias1** [ReactiveMongo/Play-ReactiveMongo#103]
It would be useful to have the Bson->Json and Json->Bson converters as a standalone jar without having to pull in the (albeit minimal) irrelevant play parts.

**Comment by cchantep** [comment]
This is still planned.

**Comment by cchantep** [comment]
Published as `"org.reactivemongo" %% "reactivemongo-play-json"`: http://search.maven.org/#search|ga|1|a%3A%22reactivemongo-play-json_2.11%22
