### ISSUE TITLE
Fix Equality Failures

### ISSUE THREAD

**Issue by reid-spencer** [ReactiveMongo/Play-ReactiveMongo#109]
There are several issues with equality in underlying bson types and buffer classes. 

ArrayReadableBuffer can be made into a case class to get the auto-generated equals method that will allow its equality to be correct. Without it, you get false negatives. 

BSONObjectID, BSONBinary and BSONDBPointer all produce false negatives for equality so they need to implement canEqual and equals for themselves.

BSONArray claims to be a BSONDocument in its toString() method.

**Comment by cchantep** [comment]
For me, this one is already fixed (see [Equality specs](https://github.com/ReactiveMongo/ReactiveMongo/blob/master/bson/src/test/scala/Equality.scala))
