### ISSUE TITLE
BSONCollection.stats deserialization error

### ISSUE THREAD

**Issue by sergeydeg** [ReactiveMongo/Play-ReactiveMongo#110]
reactivemongo_2.11-0.10.5.0.akka23.jar:0.10.5.0.akka23
After adding huge index got this error:

[DefaultCommandError: BSONCommandError['exception while deserializing this command's result!'] with original doc {
  ns: BSONString(EVES_Audit.Audit),
  count: BSONInteger(2408666),
  size: BSONDouble(1.4079607392E10),
  avgObjSize: BSONInteger(5845),
  storageSize: BSONDouble(1.574518368E10),
  numExtents: BSONInteger(27),
  nindexes: BSONInteger(4),
  lastExtentSize: BSONInteger(2146426864),
  paddingFactor: BSONDouble(1.0),
  systemFlags: BSONInteger(0),
  userFlags: BSONInteger(1),
  totalIndexSize: BSONDouble(1.837482416E9),
  indexSizes: {
    _id_: BSONInteger(78162560),
    ts: BSONInteger(60608688),
    ActId: BSONInteger(131298384),
    prmname: BSONDouble(1.567412784E9)
  },
  ok: BSONDouble(1.0)
}]

**Comment by avdv** [comment]
Hi.

That's a bug in reactivemongo. Problem is that totalIndexSize is a double, which is expected to be an int, AFAICS.

Forwarded to reactivemongo here: ReactiveMongo/ReactiveMongo#263

**Comment by cchantep** [comment]
A fix has been applied on master of ReactiveMongo about that.
