### ISSUE TITLE
Newby on nested find request

### ISSUE THREAD

**Issue by dsanchez31** [ReactiveMongo/Play-ReactiveMongo#112]
Hi,

I'm newby on scala and I try to use nested find calls (using ReactiveMongo extensions JsonDAO) with my 2.3.8 play project.

///////////////////////////////////
///////////////////////////////////

  case class TestA(_id: BSONObjectID, testB_id_set: List[BSONObjectID])
case class TestB(_id: BSONObjectID)

case class TestFullA(testA: TestA, testB_set: List[TestB])

object MyFormat {
  implicit val testAFormat = Json.format[TestA] 
  implicit val testBFormat = Json.format[TestB]
  implicit val testFullAFormat = Json.format[TestFullA]
}

///////////////////////////////////
///////////////////////////////////

object TestA_DAO extends JsonDao[TestA, BSONObjectID](ReactiveMongoPlugin.db, "collection name")
object TestB_DAO extends JsonDao[TestB, BSONObjectID](ReactiveMongoPlugin.db, "collection name")

///////////////////////////////////////////////////////
///////////////////////////////////////////////////////

I would like to do something like this

def myTestController = Action.async {

    var lResults = List[TestFullA]()
  
    // Find set of TestA from an id contained into the testB_id_set
    var lFutureTestASet = TestA_DAO.findAll("testB_id_set" $eq "some B id")
    
    lFutureTestASet.map {
      testA_set => {
        testA_set.map {
          oneTestA =>
            var lFutureTestBSet = TestB_DAO.findAll("_id" $in oneTestA.testB_id_set)

            lFutureTestBSet.map {
              testB_set => {                  
                lResults ::= TestFullA(oneTestA, testB_set)
                testB_set
              }
            }
        }
         
      }
       Ok(views.html.pageResults(lResults))
    }
} 

///////////////////////////////////
///////////////////////////////////

All is future... so how can we acheive such a request ?

Thanks !

**Comment by cchantep** [comment]
This is a broad question. It will be better to move it to the [Google Group](https://groups.google.com/forum/?fromgroups#!forum/reactivemongo) (or even the Play one).

**Comment by dsanchez31** [comment]
Hi,

Indeed I post this question and I got an answer here : https://groups.google.com/forum/#!topic/play-framework/3fBXw3lHcKM

Thansk
