### ISSUE TITLE
NaN value throws a NumberFormatException

### ISSUE THREAD

**Issue by sgodbillon** [ReactiveMongo/Play-ReactiveMongo#113]
For mongo, NaN is a double with value NaN, but reactive try to deserialize it using JsNumber(double.value) which throws a NumberFormatException.

Note: bug reported by @arussel on ReactiveMongo (https://github.com/ReactiveMongo/ReactiveMongo/issues/228), moved it here because it's related to the Play plugin only.

**Comment by cchantep** [comment]
See https://github.com/ReactiveMongo/ReactiveMongo-Play-Json/pull/33
