### ISSUE TITLE
Support for multiple connections

### ISSUE THREAD

**Issue by mgibowski** [ReactiveMongo/Play-ReactiveMongo#114]
I need to use more than one connection in my application. 

As I can see, it's not possible to do it via the Plugin, but it's possible at the level of Reactive Mongo - according to the docs:

> In some (rare) cases it is perfectly viable to create as many MongoConnection instances you need with one MongoDriver instance – in that case, you will get different connection pools. This is useful when your application has to connect to two or more independent MongoDB nodes (i.e. that do not belong to the same ReplicaSet), or different Replica Sets.

> val serversReplicaSet1 = List("rs11", "rs12", "rs13")
> val connectionReplicaSet1 = driver.connection(serversReplicaSet1)

> val serversReplicaSet2 = List("rs21", "rs22", "rs23")
> val connectionReplicaSet2 = driver.connection(serversReplicaSet2)

For me it would be very elegant, if I could create named connection configurations in the application.conf file, similar to how it is in case of SQL databases.

The default connection could stay as mongodb.uri (for the backward compatibility), and another one could be for example mongodb.other.uri

**Comment by ilya-epifanov** [comment]
+1

**Comment by cchantep** [comment]
Please have a look at the [updated documentation](http://reactivemongo.org/releases/0.11/documentation/tutorial/play2.html), mentioning the "multiple pools". The [user MailingList](https://groups.google.com/forum/?fromgroups#!forum/reactivemongo) is available for more question. Best regards.
