### ISSUE TITLE
provide `contentType` in function `serve`

### ISSUE THREAD

**Issue by agebhar1** [ReactiveMongo/Play-ReactiveMongo#119]
To prevent lock up files content type for selection of disposition mode on call of `serve`, provide the content type which is available inside `serve`. A overload version of `serve` (based on 0.10.5.x.akka23 branch) can be found here https://github.com/agebhar1/Play-ReactiveMongo/commit/6aad686bf33c625420b87dc88d891f51057f41e6

I would open a pull request but i'm not sure on which base target ...

**Comment by cchantep** [comment]
Hi @agebhar1, you can create a PR against master. Thanks.

**Comment by agebhar1** [comment]
Nice, create PR against master.
