### ISSUE TITLE
Cannot authenticate against MongoDB 3.0 from ReactiveMongo 0.10.5.0.akka23

### ISSUE THREAD

**Issue by chrismhw** [ReactiveMongo/Play-ReactiveMongo#120]
(This is my first error report on Github, so apologies if I've got the wrong place/format/approach!)

I have a MongoDB server where I have enabled authentication and created users with DB-specific permissions. The user for this app is defined as shown below i.e. geoAdmin has read, readWrite and dbOwner permissions for the relevant database:

MongoDB shell version: 3.0.0
connecting to: 192.168.2.89/test
> use geo_db
switched to db geo_db
> db.getUser("geoAdmin")
{
    "_id" : "geo_db.geoAdmin",
    "user" : "geoAdmin",
    "db" : "geo_db",
    "roles" : [
        {
            "role" : "read",
            "db" : "geo_db"
        },
        {
            "role" : "dbOwner",
            "db" : "geo_db"
        },
        {
            "role" : "readWrite",
            "db" : "geo_db"
        }
    ]
}

The following query works OK i.e. connecting to the remote server from my local mongo client:

mint:~ $ mongo 192.168.2.89:27017 -u geoAdmin -p secret --authenticationDatabase geo_db
MongoDB shell version: 3.0.0
connecting to: 192.168.2.89/test
> use geo_db
switched to db geo_db
>  db.LAD_DEC_2013_GB_BFE.findOne({},{'properties.LAD13NM':1})
{
    "_id" : ObjectId("54ffe2824f0787ec1293017f"),
    "properties" : {
        "LAD13NM" : "Hartlepool"
    }
}

I then connect to the same remote host from a ReactiveMongo Play app on the same local client, with this URL in the app config file:

`mongodb.uri = "mongodb://geoAdmin:secret@192.168.2.89:27017/geo_db"`

But when my app tries to read from the same collection, I get a MongoDB "code = 13" error:

`[DetailedDatabaseException: DatabaseException['not authorized for query on geo_db.LAD_DEC_2013_GB_BFE' (code = 13)]]`

The app works fine if I disable authentication.

I asked about this on [StackOverflow ](http://stackoverflow.com/questions/29791712/cannot-access-authenticated-mongodb-collection-from-reactivemongo-play-app) and it was suggested there was some incompatability between ReactiveMongo and MongoDB 3.0.

**Comment by cchantep** [comment]
Hi, as indicated on the [Google Group](https://groups.google.com/forum/?fromgroups#!topic/reactivemongo/gC5vLErbq8E), ReactiveMongo 0.10 is partially compatible with MongoDB 3.

Have you got your code working with ReactiveMongo 0.10 and Mongo 2.x ? If not, I would suggest to check the auth info used with ReactiveMongo is the same as the one when testing from CLI.

You can also give a try to the snapshot mentionned on the Google Group.

**Comment by chrismhw** [comment]
Thanks for the feedback.  I may try downgrading my MongoDB to 2.8 to see if it works.

**Comment by htsiah** [comment]
Hi chrismhw, 

I'm having same problem on MongoDB 3 authentication. Do you managed it works on MongoDB 2.8?

**Comment by kiranraj** [comment]
I am seeing this issue even in mongodb 2.6.8.

**Comment by imang** [comment]
mongo 2.6 uses MONGODB-CR auth protocol and 3.0 uses MONGODB-SHA-1 by default

downgrade mongodb 3.0 to MONGODB-CR 
1. login mongo noauth
2. remove any user
3. use admin database
4. update system.version collection authSchema currentVersion=3
ex.
```
use admin
db.system.version.update({ "_id" : "authSchema"},{$set: {"currentVersion" : 3} })
```

**Comment by cchantep** [comment]
The new auth must be implemented before in the core driver. A ticket is already planned: https://github.com/ReactiveMongo/ReactiveMongo/issues/327
