### ISSUE TITLE
How to properly transform Json Writes Combinator

### ISSUE THREAD

**Issue by jdauphant** [ReactiveMongo/Play-ReactiveMongo#145]
Hello,

I am having an issue with the version "0.11.2.play24" of play reactivemongo and Play Json Writes Combinator.
I have an error when I apply a transform on a Json Writes Combinator :
```
  def typeWrites[T](w : Writes[T]): Writes[T] = {
    w.transform( js =>
      js.as[JsObject] - "_type"  ++ Json.obj("type" ->  (js \ "_type").get)
    )
  }
implicit val userWrite = typeWrites[User](Json.writes[User])
```
The error message is : 
```
No Json serializer as JsObject found for type models.User. Try to implement an implicit OWrites or OFormat for this type.
Error occurred in an application involving default arguments.
```
This code works work well in play reactivemongo "0.10.5.0.akka23".

This code also return the same error :
```
  def typeWrites[T](w : Writes[T]): Writes[T] = w
implicit val userWrite = typeWrites[User](Json.writes[User])
```

Thanks for you answer,
Best regards

**Comment by cchantep** [comment]
Hi,

As indicated in the [documentation](http://reactivemongo.org/releases/0.11/documentation/tutorial/play2.html), it's recommanded to `import play.modules.reactivemongo.json._` to make the BSON/JSON conversions available.

Please first ask question on the [user MailingList]( https://groups.google.com/forum/m/?fromgroups#!forum/reactivemongo) rather than on this issue tracker.

Best regards

**Comment by jdauphant** [comment]
Hi @cchantep ,
Thanks for the anwser and sorry to have created an issue here.
The import "import play.modules.reactivemongo.json._" is already included, I will repost and provide a more complete example on the mailinglist.

My 2 cents on the problem :
The BSON/JSON conversions implementation expect OWrites and not Writes trait support (Transformation on Writes/OWrites produce Writes and not OWrites.). For Reads, it's works because the BSON/JSON conversions expect Reads API and not OReads.
