### ISSUE TITLE
Compile error after version update from 0.11.1.play24 to 0.11.2.play24

### ISSUE THREAD

**Issue by dejvid** [ReactiveMongo/Play-ReactiveMongo#152]
Hi,

dont know what I am doing wrong but after I change libraryDependency from
```
"org.reactivemongo" %% "play2-reactivemongo" % "0.11.1.play24",
```
to
```
"org.reactivemongo" %% "play2-reactivemongo" % "0.11.3.play24",
```
in `built.sbt` I get compile  error
```
No Json serializer as JsObject found for type play.api.libs.json.JsObject. Try to implement an implicit OWrites or OFormat for this type.
```

I have imports for BSON-JSON conversions as suggested on website.  
```

// BSON-JSON conversions/collection
import play.modules.reactivemongo.json._, ImplicitBSONHandlers._
import play.modules.reactivemongo.json.collection._
```

Code that triggers this compile error is
```
val filtri = dbFiltri.find(Json.obj("aktiven"->true)).cursor[VF]().collect[Seq]()
```
where dbFiltri is JSONCollection and VF is simple case class.  This code work OK with 0.11.1.play24.

What am I missing? Please help I'm stuck.

**Comment by cchantep** [comment]
Hi, please first ask such question on the [user MailingList](https://groups.google.com/forum/?fromgroups#!forum/reactivemongo).

Note that the following test about implicit resolution using 0.11.3.play23 confirm that the instances for `JsObject` are available, so it's recommanded to check the import are properly available by the code.

```scala
scala> import play.api.libs.json.{ JsObject, OWrites, Writes }
import play.api.libs.json.{JsObject, OWrites, Writes}

scala> import play.modules.reactivemongo.json._
import play.modules.reactivemongo.json._

scala> implicitly[Writes[JsObject]]
res2: play.api.libs.json.Writes[play.api.libs.json.JsObject] = play.modules.reactivemongo.json.ImplicitBSONHandlers$JsObjectDocumentWriter$@7552980c

scala> implicitly[OWrites[JsObject]]
res3: play.api.libs.json.OWrites[play.api.libs.json.JsObject] = play.modules.reactivemongo.json.ImplicitBSONHandlers$JsObjectDocumentWriter$@7552980c
```

Best regards

**Comment by chuchao333** [comment]
@cchantep 
I have exactly the same compile error. The exactly the same code compiles in 0.11.1.play23 but got the above "No Json serializer as JsObject found for type play.api.libs.json.JsObject. Try to implement an implicit OWrites or OFormat for this type." in newer versions. There must be something wrong in the version since 0.11.2.play23 (0.11.2.play23 - 0.11.6.play23). Could you please double check? Thanks!

**Comment by cchantep** [comment]
@chuchao333 As indicated, this issue tracker is for confirmed issue. Please move your question to the [user MailingList](https://groups.google.com/forum/?fromgroups#!forum/reactivemongo).
