### ISSUE TITLE
ReactiveMongoPlugin deprecated for Play 2.3?

### ISSUE THREAD

**Issue by zoltanmaric** [ReactiveMongo/Play-ReactiveMongo#169]
Hi contributors!

First of all, thank you for this clever project!

I'm trying to migrate my project from using `play2-reactivemongo` version `0.10.5.0.akka23` to using version `0.11.7.play23`. It is important to note that I'm using Play **2.3**.

The [documentation for Play 2.4][1] says that I should use `ReactiveMongoModule` and `ReactiveMongoApi`, but `ReactiveMongoApi` is only available in version `0.11.7.play24`.<br>
It doesn't say anything about how to use it with Play 2.3, so I assumed I was still supposed to use `ReactiveMongoPlugin`. However, I'm still getting deprecation warnings on the use of `ReactiveMongoPlugin`:
```
object ReactiveMongoPlugin in package reactivemongo is deprecated: Use ReactiveMongoModule and ReactiveMongoApi.
```
Is the deprecation warning incorrect for version `0.11.7.play23`, or is there another way of accessing the API?

  [1]: http://reactivemongo.org/releases/0.11/documentation/tutorial/play2.html#play-24

**Comment by cchantep** [comment]
Hi, please rather use the [user MailingList](https://groups.google.com/forum/?fromgroups#!forum/reactivemongo) to ask question (this tracker is for confirmed issue/actionable feature request). Best regards.
