### ISSUE TITLE
blue insert error

### ISSUE THREAD

**Issue by binkabir** [ReactiveMongo/Play-ReactiveMongo#172]
Hi All, Im having an issue with reactivemongo

Im using ubuntu 15.04 OS with play2.4 and reactivemongo plug-in 0.11.7

whenever I try to do a bulk insert operation somethings i get an error like this

    [error] - reactivemongo.core.actors.MongoDBSystem - The entire node set is unreachable, is there a network problem?

while MOST times ONLY a few of the records are actually inserted into the mongodb.

have anyone experienced such? 

Thanks.

**Comment by cchantep** [comment]
Hi, please use the [mailing list](https://groups.google.com/forum/m/?fromgroups#!forum/reactivemongo) to ask for help/question. This tracker is for confirmed issue. Best regards.
