### ISSUE TITLE
 self-type controllers.Users does not conform to play.modules.reactivemongo.MongoController's

### ISSUE THREAD

**Issue by singhakash** [ReactiveMongo/Play-ReactiveMongo#175]
I am trying to create a play mongo app .I added ` "org.reactivemongo" %% "play2-reactivemongo" % "0.11.2.play24"` and created a controller

`class Users extends Controller with MongoController`

But when I am trying to compile it shows
```
[error]  self-type controllers.Users does not conform to play.modules.reactivemongo.MongoController's selftype play.modules.rea
ctivemongo.MongoController with play.api.mvc.Controller with play.modules.reactivemongo.ReactiveMongoComponents
[error] class Users extends Controller with MongoController
[error]                                     ^
[error] one error found
[error] (compile:compile) Compilation failed
[error] Total time: 9 s, completed Dec 20, 2015 4:00:15 PM
```

**Comment by ezzahraoui** [comment]
Please try :
```scala
// ReactiveMongo Play2 plugin
import play.modules.reactivemongo.{ 
  MongoController,
  ReactiveMongoApi,
  ReactiveMongoComponents
}

class Users @Inject()(val reactiveMongoApi: ReactiveMongoApi) extends Controller with MongoController with ReactiveMongoComponents 
```

**Comment by singhakash** [comment]
Thanks it compiled but can you explain why it wont work with my code as I am just a beginner with scala rectivemongo.

**Comment by cchantep** [comment]
Hi, this issue tracker is for confirmed issue. Please use the [MailingList](https://groups.google.com/forum/m/?fromgroups#!forum/reactivemongo) for discussion (or to ask first if you're not sure). The document is [available online](http://reactivemongo.org/). Best regards.
