### ISSUE TITLE
Dropping collections should have the same behaviour

### ISSUE THREAD

**Issue by agusgambina** [ReactiveMongo/Play-ReactiveMongo#180]
When I wrote tests for the collection *users* were all working fine.

But when I wrote tests for the collection *tokens*, at first were not working. It raised this exception

```
[info] - should Persist and find a token * FAILED * 
[info] The future returned an exception of type: reactivemongo.api.commands.bson.DefaultBSONCommandError, with message: CommandError[code=26, errmsg=ns not found, doc: {
[info] ok: BSONDouble(0.0), 
[info] errmsg: "ns not found",
[info] code: BSONInteger(26)
[info] }].
```

It seems that the problem was that I was trying to drop a collection that did not exist.

Manually I got into the mongo console I created the collection *tokens*, after that, when I run the test again it turned out that they worked.

Maybe this is not an issue and I am wrong, but it would be excellent if they could have the same behaviour with every collection.

Thank you!

**Comment by cchantep** [comment]
Hi, the place to ask for question is the [MailingList](https://groups.google.com/forum/?fromgroups#!forum/reactivemongo) (this issue tracker is dedicated to confirm issue). Best regards.

**Comment by cchantep** [comment]
See reactivemongo#437
