### ISSUE TITLE
Trying to query before full authentication with mongolab

### ISSUE THREAD

**Issue by Hajto** [ReactiveMongo/Play-ReactiveMongo#185]
I'm using Play 2.4 with plugin version 0.11.2.play24.

Querry is sent before proper authentication as seen in logs. That's not an issue for local server, but it is for remotes. Using Scram SHA-1 authentication.

When app is started i get error code = 13 as response to first request. The error log:
https://gist.github.com/Hajto/44c530ef790618ee274f

Due to courtesy of MongoLab Employee:
```
mongodb.log.2016-02-22T09-42-47:2016-02-21T11:26:13.764-0800 I NETWORK  [initandlisten] connection accepted from #IPADDRESS
mongodb.log.2016-02-22T09-42-47:2016-02-21T11:26:14.177-0800 I QUERY    [conn18373] assertion 13 not authorized for query on test.Project test.Project query:{}
mongodb.log.2016-02-22T09-42-47:2016-02-21T11:26:14.177-0800 I QUERY    [conn18373]  ntoskip:0 ntoreturn:12
mongodb.log.2016-02-22T09-42-47:2016-02-21T11:26:14.545-0800 I ACCESS   [conn18373] Successfully authenticated as principal play on zajawieni_deb
```

And code:
```
class Application @Inject() (val reactiveMongoApi: ReactiveMongoApi)
    extends Controller with MongoController with ReactiveMongoComponents
    with I18nSupport
    with Collections {

  def index = Action.async { implicit req =>
    for {
      projects <- ProjectCollection.find($()).options(QueryOpts().batchSize(12)).cursor[Project]().collect[Seq]()
    } yield Ok(views.html.index(projects))
  }

}
```

```
trait Collections { this: MongoController =>

  def getCollection(s: String): JSONCollection = db.collection(s)

  def ProjectCollection = getCollection("Project")
}
```

**Comment by cchantep** [comment]
Hi, please use the MailingList to ask question (rather than this tracker for confirmed issue). BTW you can have a look at the [discussion](https://groups.google.com/forum/?fromgroups#!topic/reactivemongo/x3OZ6-hIIXk) indicating such issue is fixed with more recent minor release 0.11.9 and 0.11.10. Best regards.
