### ISSUE TITLE
0.11.2.play24 Not in maven central

### ISSUE THREAD

**Issue by dstibbe** [ReactiveMongo/Play-ReactiveMongo#189]
Documentation in README.md  points to 
[0.11.10.play23 ](http://search.maven.org/#artifactdetails%7Corg.reactivemongo%7Cplay2-reactivemongo_2.11%7C0.11.10.play23-20160201%7C)

**Comment by cchantep** [comment]
Hi, if you have a look at the indicated [documentation](http://reactivemongo.org/releases/0.11/documentation/tutorial/play2.html), you can see that the latest version is 0.11.10 . You could also use search.maven.org to check. Best regards.

> Please first ask the [MailingList](https://groups.google.com/forum/m/?fromgroups#!forum/reactivemongo).
