### ISSUE TITLE
play.api.libs.json.JsResultException when using the Aggregation Framework

### ISSUE THREAD

**Issue by alifirat** [ReactiveMongo/Play-ReactiveMongo#194]
Hi, 

These days, I'm playing with the Aggregation Framework and I get one issue that I cannot solved myself. Before to make to aggregation with your plugin, I did it using mongochef and it works. The context of this issue that I want to aggregate the following queries : 

1. A Match 
2. An Unwind 
3. A Project 
4. A Match 

To test it for the first time, I just tried to do an unwind but an exception is raised. Below the function in which the exception is raised : 

```
import play.modules.reactivemongo.ReactiveMongoApi
import play.modules.reactivemongo.json._
import reactivemongo.play.json.collection.{JSONCollection, JsCursor}

def getAnnotations(request : AnnotationsRequest) = {
    val col = reactiveMongoApi.db.collection[JSONCollection]("collection")
    import col.BatchCommands.AggregationFramework.{AggregationResult, Match, Project, Unwind}
    val unwind = Unwind("annotations")
    val futureRes: Future[AggregationResult] = col.aggregate(unwind,List(), true, true)
    futureRes
}
```
The exception that I get : 

`play.api.libs.json.JsResultException: JsResultException(errors:List((,List(ValidationError(List('result' is undefined on object: {"stages":[{"$cursor":{"query":{},"queryPlanner":{"plannerVersion":1,"namespace":"","indexFilterSet":false,"parsedQuery":{"$and":[]},"winningPlan":{"stage":"COLLSCAN","filter":{"$and":[]},"direction":"forward"},"rejectedPlans":[]}}},{"$unwind":"$annotations"}],"ok":1}),WrappedArray())))))
`

build.sbt : 

```
libraryDependencies ++= Seq(
  cache,
  ws,
  "com.amazonaws" % "aws-java-sdk" % "1.10.12",
  "org.reactivemongo" %% "play2-reactivemongo" % "0.11.10",
  "com.github.nscala-time" %% "nscala-time" % "2.6.0"
)
```

In the test folder, I cannot see some examples using the Aggregation Framework. So, what I missing here ?

Thanking you in advance, Ali-Firat.

**Comment by cchantep** [comment]
Hi,

Do you have tried the same aggregate op using Mongo shell? What its the result?

> P.S. The aggregation documentation is available in the [online documentation](http://reactivemongo.org/releases/0.11/documentation/advanced-topics/aggregation.html).

**Comment by alifirat** [comment]
I changed a little bit my function according the documentation (I use BSONCollection instead of JSONCollection) and now the runtime exception is quite different : 

```
play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[DocumentKeyNotFound: The key 'cursor' could not be found in this document or array]]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:254) ~[play_2.11-2.4.0.jar:2.4.0]
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:180) ~[play_2.11-2.4.0.jar:2.4.0]
	at play.api.GlobalSettings$class.onError(GlobalSettings.scala:179) [play_2.11-2.4.0.jar:2.4.0]
	at play.api.DefaultGlobal$.onError(GlobalSettings.scala:212) [play_2.11-2.4.0.jar:2.4.0]
	at play.api.http.GlobalSettingsHttpErrorHandler.onServerError(HttpErrorHandler.scala:94) [play_2.11-2.4.0.jar:2.4.0]
Caused by: reactivemongo.bson.exceptions.DocumentKeyNotFound: The key 'cursor' could not be found in this document or array
	at reactivemongo.bson.BSONDocument$$anonfun$getTry$2.apply(types.scala:61) ~[reactivemongo-bson_2.11-0.11.10.jar:0.11.10]
	at reactivemongo.bson.BSONDocument$$anonfun$getTry$2.apply(types.scala:61) ~[reactivemongo-bson_2.11-0.11.10.jar:0.11.10]
	at scala.Option.getOrElse(Option.scala:121) ~[scala-library-2.11.7.jar:na]
	at reactivemongo.bson.BSONDocument.getTry(types.scala:61) ~[reactivemongo-bson_2.11-0.11.10.jar:0.11.10]
	at reactivemongo.bson.BSONDocument.getAsTry(types.scala:97) ~[reactivemongo-bson_2.11-0.11.10.jar:0.11.10]


```

The updated code : 

  ```
def getAnnotations(request : AnnotationsRequest) = {
    val col = reactiveMongoApi.db.collection[BSONCollection]("lab_records")
    import col.BatchCommands.AggregationFramework.{AgnnregationResult, Match, Project, Unwind}
    val unwind = Unwind("annotations")
    val futureRes = col.aggregate(unwind,List(), true, true).map(_.documents)
    futureRes
  }
```

**Comment by cchantep** [comment]
What is the MongoDB version? What are the result in Mongo shell?

**Comment by alifirat** [comment]
The mongodb is hosted in Heroku and his current version is 3.0.4. In Mongo shell, when I execute  `db.lab_records.aggregate( [ { $unwind : "$annotations"} ] ).pretty()`, I got no error and the annotations array is deconstructed like excepted.

**Comment by cchantep** [comment]
So what is the result you get? W/O these details, it's hard to understand what's happening.

**Comment by alifirat** [comment]
Output of the following commands : 

`db.lab_records.aggregate( [ { $unwind : "$annotations"}, {$limit : 2} ] ).pretty()
`

```
{
	"_id" : ObjectId("566976747938a7a39564370a"),
	"annotations" : {
		"id" : "566975d4a00100a001175590",
		"label" : "1046000100102",
		"category" : "clinical annotations",
		"startTime" : 1210685273171000,
		"endTime" : 1210685273171000,
		"typeStr" : "manual",
		"desc" : "no desc"
	}
}
{
	"_id" : ObjectId("566976747938a7a39564370a"),
	"annotations" : {
		"id" : "566975d4a00100a00117634f",
		"label" : "1046000200102",
		"category" : "clinical annotations",
		"startTime" : 1210748769784950,
		"endTime" : 1210748769785150,
		"typeStr" : "spike",
		"desc" : "no desc"
	}
}

```

**Comment by cchantep** [comment]
Hi @alifirat 

Calling `col.aggregate(unwind,List(), true, true)` you are using `explain = true`, that's why you get [`explain` result](https://docs.mongodb.org/manual/reference/method/db.collection.aggregate/#return-information-on-aggregation-pipeline-operation) instead of aggregation result:

```json
{"stages":[{"$cursor":{"query":{},"queryPlanner":{"plannerVersion":1,"namespace":"","indexFilterSet":false,"parsedQuery":{"$and":[]},"winningPlan":{"stage":"COLLSCAN","filter":{"$and":[]},"direction":"forward"},"rejectedPlans":[]}}},{"$unwind":"$annotations"}],"ok":1}
```

So first, do not call it with `explain = true`.

> Check you are using the [right JSON imports](http://reactivemongo.org/releases/0.11/documentation/json/overview.html): `import reactivemongo.play.json._` instead of the former `import play.modules.reactivemongo.json._`

**Comment by alifirat** [comment]
Hi, 

Thanks you for your explanation. But it seems like there is an another problem about the `allowDiskUse` option. From the official documentation about this option : 

```
Aggregate Data using External Sort

Aggregation pipeline stages have maximum memory use limit. To handle large datasets, set allowDiskUse option to true to enable writing data to temporary files, as in the following example:

db.runCommand(
   { aggregate: "stocks",
     pipeline: [
                 { $project : { cusip: 1, date: 1, price: 1, _id: 0 } },
                 { $sort : { cusip : 1, date: 1 } }
               ],
     allowDiskUse: true
   }
)

```

What I did : 

 ```
def getAnnotations(request : AnnotationsRequest) = {
    val col = reactiveMongoApi.db.collection[JSONCollection]("mycollection")
    import col.BatchCommands.AggregationFramework.{AggregationResult, Match, Project, Unwind, Limit}

    val matchAnnotations = Match(Json.obj("annotations" -> Json.obj("$exists" -> true, "$ne" -> List[Annotation]())))
    val unwind = Unwind("annotations")
    val futureRes : Future[List[JsObject]] =
      col.aggregate(matchAnnotations,List(unwind), explain=false, allowDiskUse=true) map (_.firstBatch) 
      // col.aggregate(firstOperator:PipelineOperator, otherOperators:List[PipelineOperator], explain:Boolean, allowDiskUse:Boolean, bypassDocumentValidation:Boolean, readConcern:Option[ReadConcern])=>(ec:ExecutionContext)
    val jsRecords : List[JsObject] = Await.result(futureRes, 10.seconds)
    val annotations = jsRecords map (jsObj => (jsObj \ "annotations").as[Annotation])
    Logger.info(annotations.size.toString())
    annotations
  }
```

But I get an runtime exception : 

`play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[RuntimeException: (,List(ValidationError(List(CommandError[code=16389, errmsg=exception: aggregation result exceeds maximum document size (16MB), doc: {"errmsg":"exception: aggregation result exceeds maximum document size (16MB)","code":16389,"ok":0}]),WrappedArray())))]]`

The mongoDB instance is hosted on `Heroku `and his version is `3.0.4`. Making the same query in mongo shell (3.2.5) works. Should I open an new issue for that or the problem comes from the mongo version hosted on Heroku ? 

Thanks, alifirat.

**Comment by cchantep** [comment]
I don't think that's related to the driver, but to the MongoDB different.

> Please use the [MailingList](https://groups.google.com/forum/?fromgroups#!forum/reactivemongo) to first ask question.

Best regards
