### ISSUE TITLE
How can I use Match OR in aggregation

### ISSUE THREAD

**Issue by sopheakreth** [ReactiveMongo/Play-ReactiveMongo#225]
In mongo I used it

![image](https://cloud.githubusercontent.com/assets/19568260/21383542/e005d0ce-c798-11e6-9bd7-3e5e439f6c65.png)

My coding here, it's not work. So how can I apply it in to play scala

![image](https://cloud.githubusercontent.com/assets/19568260/21383508/ac97443e-c798-11e6-9b7d-9799abe70b00.png)

**Comment by cchantep** [comment]
Hi, as [indicated](https://github.com/ReactiveMongo/Play-ReactiveMongo/blob/master/.github/ISSUE_TEMPLATE.md#are-you-looking-for-help), please do not use this issue tracker to ask question/for help, but the [MailingList](https://groups.google.com/forum/?fromgroups#!forum/reactivemongo). Best regards.
