### ISSUE TITLE
No way to mix in reactive mongo configured from configuration to a Play app

### ISSUE THREAD

**Issue by jroper** [ReactiveMongo/Play-ReactiveMongo#245]
If you're using the thin cake pattern with Play, and you want to configure reactive mongo from configuration, the only way you can do that (without using any deprecated methods) currently is to use `ReactiveMongoApiFromContext`. The problem is, that is an abstract class, not a trait, and so it can't be mixed into an application trait. If every database were to do this, eg you might have `RedisFromContext`, then it would be impossible to use them together, since you can't mix abstract classes together. So Play libraries should never, ever use abstract classes to provide components for the thin cake pattern.

So, that means you can't use `ReactiveMongoApiFromContext` in anything but the most trivial of apps, meanwhile `ReactiveMongoApiComponents` is useless because it doesn't provide any implementations of the methods. Then, there are no public or non deprecated APIs available that actually allow you to pass a `Configuration` and get back a parsed config, for example `DefaultReactiveMongoApi.parseConfiguration` is `private[reactivemongo]`, and all the `new DefaultReactiveMongoApi` overloads that take `Configuration` are deprecated.

I think `ReactiveMongoApiComponents` should be modified to have all the logic from `ReactiveMongoApiFromContext`, and `ReactiveMongoApiFromContext` should be deleted.

**Comment by cchantep** [comment]
Having`DefaultReactiveMongoApi.parseConfiguration` private makes sense, as since 0.11 the config should only be done using the connection URI, which is provided in the public API (not specific to Play plugin) by [MongoConnection.parseURI](http://reactivemongo.org/releases/0.12/api/index.html#reactivemongo.api.MongoConnection$@parseURI(uri:String):scala.util.Try[reactivemongo.api.MongoConnection.ParsedURI]).

The legacy config parsing is not recommanded, and should not be used in custom ReactiveMongo setup.

**Comment by jroper** [comment]
But that's not the point - are you saying that now the best practice is to only programatically configure reactive mongo by using the `MongoConnection.parseURI` method? So every Play user (that's using compile time DI) is expected to manually invoke `MongoConnection.parseURI` themselves? Or is there supposed to be an out of the box way to configure reactive mongo from `application.conf`? Because right now, when using compile time DI, there is no out of the box way, apart from using an abstract class that can't be mixed in to a regular cake.

**Comment by cchantep** [comment]
The "out of the box way" is provided by the `ReactiveMongoApiFromContext`.

The trait `ReactiveMongoApiComponents` was introduced to be able to customize the resolution/loading of the configuration, that's to say for now that resolution of the connection URI.

Parsing URI from `application.conf` is quite trial using injected (or whatever) `Configuration.getString` + `.parseURI`. Maybe the [doc](http://reactivemongo.org/releases/0.12/documentation/tutorial/connect-database.html#connect-using-mongodb-uri) can be improved about that, but for me providing such one-liner as API has quite no value

**Comment by sidthesloth** [comment]
Hi, I know this issue is closed but has anyone with a working example of using react ReactiveMongo and macwire compile time DI

**Comment by cchantep** [comment]
Please @sidthesloth do not use issue to discuss/ask question (specially closed issue). Use the [MailingList](https://groups.google.com/forum/m/#!forum/reactivemongo) or SO.
