### ISSUE TITLE
RuntimeException: The global application is disabled. The reason is usage of the deprecated feature

### ISSUE THREAD

**Issue by anatse** [ReactiveMongo/Play-ReactiveMongo#250]
Hello. Please help me to fix error|bag.

### Expected Behavior

Call of function play.modules.reactivemongo.DefaultReactiveMongoApi.database should return database object. 

### Actual Behavior

Throws an exception - RuntimeException: The global application is disabled.
The reason is here when it's tried to aсquire defaultContest
```scala
def database: Future[DefaultDB] = {
    import play.api.libs.concurrent.Execution.Implicits.defaultContext

    logger.debug(s"Resolving database '$dbName' ... ($parsedUri)")
    connection.database(dbName)
  }
```
Exception throws in class play.api.libs.concurrent.Execution in which we can see next message - "deprecated(Please see https://www.playframework.com/documentation/2.6.x/Migration26...)"

```scala
@deprecated("Please see https://www.playframework.com/documentation/2.6.x/Migration26#play.api.libs.concurrent.Execution-is-deprecated", "2.6.0")
object Execution {
  object Implicits {
    implicit def defaultContext: ExecutionContext = CoreExecution.internalContext
  }
  def defaultContext: ExecutionContext = CoreExecution.internalContext
}
```

### Reproducible Test Case

Put in application.conf file next line:
play.allowGlobalApplication = false

**Comment by cchantep** [comment]
As indicated in the guide lines, please as the [MailingList](https://groups.google.com/forum/?fromgroups#!forum/reactivemongo).
