### ISSUE TITLE
Fail to test with specs2

### ISSUE THREAD

**Issue by montesq** [ReactiveMongo/Play-ReactiveMongo#32]
Hello and thank you for you job on ReactiveMongo

When I try to test my app with specs2, the first test is OK but the second one is always KO (whereas the test is EXACTLY the same as the first one, except for the name). 
I get the message:

[info] + insert a new account
[error] ! insert a new account2
[error]     TimeoutException: Futures timed out after [10000 milliseconds] (Promise.scala:96)

Does it come from the mongodb server configuration, from my code or from ReactiveMongo?

FYI, the controller I try to test is 

object Accounts extends Controller with MongoController{

  val collection = db.collection[JSONCollection]("accounts")

  def createAccount = Action(parse.json) { request =>
    request.body.transform(validateAccount).map{ json =>
      Async{
        collection.insert(json).map{lastError =>
          Created
        }.recover{ case e =>
          BadRequest(JsString("exception %s".format(e.getMessage)))
        }
      }
    }.recoverTotal{ err =>
      BadRequest(JsError.toFlatJson(err))
    }
  }

The test is 

class AccountSpec extends Specification {
  "Account" should {
    "insert a new account" in new WithApplication {
      val json = Json.obj(
        "technical_name" -> "test",
        "name" -> "test"
      )

      val Some(result) = route(FakeRequest(POST, "/accounts").
        withJsonBody(json))

      status(result) must equalTo(CREATED)
    }

    "insert a new account" in new WithApplication {
      val json = Json.obj(
        "technical_name" -> "test",
        "name" -> "test"
      )

      val Some(result) = route(FakeRequest(POST, "/accounts").
        withJsonBody(json))

      status(result) must equalTo(CREATED)
    }
  }
}

**Comment by WuWeiming** [comment]
Here is a working test, for multiple test classes.
You can read the documentation in https://www.playframework.com/documentation/2.2.x/ScalaFunctionalTestingWithScalaTest
http://doc.scalatest.org/plus-play/1.0.0/index.html#org.scalatestplus.play.ConfiguredApp

import play.api.test._
import org.scalatest._
import org.scalatestplus.play._
import play.api.{Play, Application}

//master test class that triggers the other test class, the FakeApplication is initialized in this class before //all other test classes
class MasterSpec extends Suites(
	new AuthenticationTest,
	new AccountTest
) with OneAppPerSuite {
	//your configuration for the  FakeApplication
}

class TestSpec1 extends PlaySpec with ConfiguredApp {
    //your test code
}

class TestSpec2 extends PlaySpec with ConfiguredApp {
  // your test code
}

**Comment by cchantep** [comment]
Hi, I suspect that issue if more related to the lifecycle of Play plugin (which will be changed in the next Play release and already have been updated for some 2.3.x minor versions). I guess for now that would be better to run test with a connection manager by tests themselves (rather than a fake Play app).
