### ISSUE TITLE
Number values gets always insert as double values

### ISSUE THREAD

**Issue by akkie** [ReactiveMongo/Play-ReactiveMongo#33]
If I understand the implementation correct, then all number values inside a JSON string gets inserted as double values.

As described in the [Play/Json documentation](http://www.playframework.com/documentation/2.1.1/ScalaJson), all numbers are stored as JsNumber. And this type uses internal a BigDecimal.

>> JsNumber
>> JSON does NOT discriminate short, int, long, float, double, bigdecimal so it is represented by JsNumber containing a bigdecimal.

The problem is that that the [BSONDoubleFormat.partialReads](https://github.com/zenexity/Play-ReactiveMongo/blob/master/src/main/scala/play/modules/reactivemongo/json.scala#L38) method matches always the ```JsNumber``` type, because it is [defined](https://github.com/zenexity/Play-ReactiveMongo/blob/master/src/main/scala/play/modules/reactivemongo/json.scala#L210) before all other number types.

**Comment by cchantep** [comment]
See #116
