### ISSUE TITLE
Fails to send isMaster

### ISSUE THREAD

**Issue by mohdmsl** [ReactiveMongo/Play-ReactiveMongo#486]
I am using play with reactive mongo  
"org.reactivemongo" %% "play2-reactivemongo" % "1.1.0-play28-RC3"

and getting below error:
**[[31merror[0m] r.c.a.MongoDBSystem - [Supervisor-1/datapipeline] Fails to send a isMaster request to mongodb-1.mongodb-headless.mongodb.svc.cluster.local:27017 (channel #e7e125a4)
reactivemongo.io.netty.channel.StacklessClosedChannelException: null
at reactivemongo.io.netty.channel.AbstractChannel$AbstractUnsafe.write(Object, ChannelPromise)(Unknown Source)**

can you please provide a fix for this

**Comment by Balaram-RJS** [comment]
can this be a gc pause issue ??

**Comment by cchantep** [comment]
Hi,

As indicated question must be ask on the MailingList.
Moreover this is about driver, not Play integration.
