### ISSUE TITLE
Update method

### ISSUE THREAD

**Issue by yudao** [ReactiveMongo/Play-ReactiveMongo#56]
Hi,

I'm trying to use securesocial with reactivemongo for backend and this great plugin.

All is done except an issue.

When I try to save a JsObject with an _id, it recreate a new document with the same _id. So instead of rewrite some properties of the object corresponding to the _id passed, it create a new document.

In step by step debug mode I can see that it run the good method (update) when the _id is present on the object or not (insert).

This is the part that don't works as expected:
<pre>
val saveJson = Json.obj(
      "userid" -> user.identityId.userId,
      "provider" -> user.identityId.providerId,
      "firstname" -> user.firstName,
      "lastname" -> user.lastName,
      "username" -> user.fullName,
      "email" -> email,
      "avatar" -> avatar,
      "authmethod" -> user.authMethod.method,
      "password" -> password,
      "created_at" -> Json.obj("$date" -> new Date()),
      "updated_at" -> Json.obj("$date" -> new Date())
    )

    find(user.identityId) match {
      case Some(existUser) => collection.save(saveJson.++(Json.obj("_id" -> existUser.oi))).onComplete {
        case Failure(e) => throw e
        case Success(_) => println("successful!")
      }
      case _ => collection.save(saveJson)
    }
</pre>

Maybe am I wrong on the implementation? But I have tested a lot of behaviors and it always the same result.

Thanks.

**Comment by cchantep** [comment]
Closing it for now. Do not hesitate to add any new feedback. Best regards.
