### ISSUE TITLE
Play 3.0 support

### ISSUE THREAD

**Issue by tardigradeus** [ReactiveMongo/Play-ReactiveMongo#564]
### ReactiveMongo Version
1.1.0-RC12

### MongoDB version (2.6, 3.0 / etc)
Not important

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)
Not important

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)
Not important

### Library Dependencies

Play framework 3.0.2

### Expected Behavior
1. There is a release for Play 3.0

### Actual Behavior
1. There is no release for Play 3.0

I'll create a PR with the modifications to support Pekko.

**Comment by gaeljw** [comment]
Apologies if not the best place to ask but I see the Play 3 releases are still RC (`"1.1.0-play30.RC14"` right now). Could you where why the RC status? Is there anything we should be aware of if we use this version in production?

**Comment by cchantep** [comment]
https://groups.google.com/g/reactivemongo/c/8D1EFbBpu7s
