### ISSUE TITLE
README example comment is misleading

### ISSUE THREAD

**Issue by stewartmatheson** [ReactiveMongo/Play-ReactiveMongo#67]
```
// transform the list into a JsArray
val futurePersonsJsonArray: Future[JsArray] = futurePersonsList.map { persons =>
  Json.arr(persons)
}
```

The above comment implies that a transformation will happen but in actual fact Json.arr() will wrap any list it's passed resulting in a list of lists which is not what most people would want. Is there any chance of updating this as I am stuck with an array of arrays. Thanks for your time.

**Comment by cchantep** [comment]
Right, it should be `Json.arr(persons: _*)`

**Comment by cchantep** [comment]
Fixed in the new documentation. Thanks.
