### ISSUE TITLE
Performance Drops When Using Tailable Cursors

### ISSUE THREAD

**Issue by michaelahlers** [ReactiveMongo/Play-ReactiveMongo#75]
I've encountered a huge drop in performance when a tailable cursor is open on a capped collection that sends records over a WebSocket (informed by and following @sgodbillon's [tailable cursor example](http://github.com/sgodbillon/reactivemongo-tailablecursor-demo) almost exactly).

I've a capped collection which stores notifications, and various other collections for data. Any time a tailable cursor is open to receive records from the notification collection (which sends them down a WebSocket), _all_ web services retrieving data from other collections take significantly longer to respond. If I disable code that opens the with the tailable cursor, all other services predictably and reliably return to their expected performance. Nominal response times are sub-100 ms (usually less). Response times on those same services with the tailable cursor open are always above several seconds.

This could be a bug in be a bug in [ReactiveMongo](http://github.com/ReactiveMongo/ReactiveMongo) proper, but I want to raise the issue sooner as I start digging.

**Comment by alrouen** [comment]
Hi,

I had exactly the same issue. And so far the only way for me to avoid that was to use this kind of hack:

- use the regular db object from the reactivemongo play plugin to open any collections on which I will use for regular queries. ( ReactiveMongoPlugin.db.collection[[JSONCollection]]("my collection") )

- use a specific db object to open any collections on which I will use tailable cursor. (ReactiveMongoPlugin.driver.connection(...) / connection.db(dbName).collection[[JSONCollection]](collectionName) )

By doing that all regular queries seems to not be impacted by this bug. 

By the way, the root issue seems to come from the .awaitData option.

**Comment by michaelahlers** [comment]
@alrouen, I haven't yet had time to verify, but is this at all related to the Akka `ActorSystem` intrinsically shared by all clients using the singleton `DB` object produced in [`play.modules.reactivemongo.ReactiveMongoHelper`](https://github.com/ReactiveMongo/Play-ReactiveMongo/blob/fea4b33e95f58f4f386fdc8a59ff6b14c4b52aba/src/main/scala/play/modules/reactivemongo/ReactiveMongoPlugin.scala#L162) (which, by the way, uses Scala's global `ExecutionContext`)? I addressed an unrelated performance issue by creating our own `DB` instances (allowing thread configuration per [Play's documentation](https://www.playframework.com/documentation/2.3.x/ThreadPools)).

**Comment by cchantep** [comment]
Close it for now. Let way for feedback concerning more recent releases.
