### ISSUE TITLE
Issue with ReactiveMongo 'serve' method

### ISSUE THREAD

**Issue by karthikponmudi** [ReactiveMongo/Play-ReactiveMongo#89]
I have a strange issue with ReactiveMongo plugin(0.10.2), used to store and serve videos using MongoDB GridFS. I could store the video files from latest andriod(.mp4) and iphone(.mov) in reactive manner with help of gridFsBodyParser. But when I try to stream the file using serve method, the file is returned empty. This issue happens only for the videos taken from Android Phones or iPhone. If I upload other videos(not taken by mobile phone), every think works fine.

There is no problem in storing the videos, because I could download the videos from MongoDB by using salat plugin from another application, but the ReactiveMongo plugin failed to serve the videos taken from mobile phones(android and iphone). The issue might be in enumerate method call in serve method, but I dont know, exactly where and what the issue is.

Could any one, help me on solving this issue?

**Comment by cchantep** [comment]
Closing it for now. Let consider it again if it can reproduced after the release of 0.11. Best regards.
