### ISSUE TITLE
Library not found

### ISSUE THREAD

**Issue by lincolnmatra** [ReactiveMongo/Play-ReactiveMongo#90]
I'm getting the following error:
warn]   ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: org.reactivemongo#reactivemongo_2.10;0.11.0-SNAPSHOT: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[trace] Stack trace suppressed: run last *:update for the full output.
[error](*:update) sbt.ResolveException: unresolved dependency: org.reactivemongo#reactivemongo_2.10;0.11.0-SNAPSHOT: not found
[error] Total time: 2 s, completed Jun 12, 2014 2:02:44 AM

I'm using Play 2.3 and my build.sbt is setup as follows:
version := "1.0-SNAPSHOT"

lazy val root = (project in file(".")).enablePlugins(PlayScala)

//scalaVersion := "2.11.1"

//Reactive Mongo Scala Driver
resolvers += "Sonatype Snapshots" at "http://oss.sonatype.org/content/repositories/snapshots/"

libraryDependencies ++= Seq(
  jdbc,
  anorm,
  cache,
  ws,
  "org.webjars" % "bootstrap" % "3.0.1",
  "org.reactivemongo" %% "reactivemongo" % "0.11.0-SNAPSHOT"
)

I've also tried the following libraries:
"org.reactivemongo" %% "play2-reactivemongo" % "0.11.0-SNAPSHOT"
"org.reactivemongo" %% "play2-reactivemongo" % "0.10.5.akka23-SNAPSHOT"

**Comment by gauravnavgire** [comment]
Added "resolvers += "Sonatype Snapshots" at "https://oss.sonatype.org/content/repositories/snapshots/"" as mentioned in above posts. But I'm still facing the same problem. The error message is "object modules is not a member of package play" for "import play.modules.reactivemongo.ReactiveMongoApi"

**Comment by cchantep** [comment]
Hi @gauravnavgire , as indicated in the guidelines, please ask question/for help on the [MailingList](https://groups.google.com/forum/?fromgroups#!forum/reactivemongo). This tracker is for confirmed issue.
