### ISSUE TITLE
Documentation: how to respond to errors

### ISSUE THREAD

**Issue by ErunamoJAZZ** [ReactiveMongo/Play-ReactiveMongo#95]
Testing with ReactiveMongo, I had a problematic on how to respond appropriately in the event of an exception.

(The case when try insert, and "_id" exists)

After struggling these days, and learn how work Futures in Scala, and all that, this was the solution I found.
I would that you added to the examples, because it can be an important use case.

```scala
def create(json: JsValue) = Action.async {
    // insert a json
    val futureResult = collection.insert(json)
    // Note flatMap
    futureResult.flatMap{ lastError =>
        Future.successful(Ok)
      } recover { 
        case e: Throwable => BadRequest
      }
  }
```

ty :)

**Comment by cchantep** [comment]
Error handling using `Future` is not specific to ReactiveMongo (and the [documentation](http://reactivemongo.org/releases/0.10.5/documentation/tutorial/write-documents.html) mentions some examples about that).
